### PR TITLE
bug found, isOddLeaf is changed to isOdd

### PR DESCRIPTION
**Pull request by KedarKK1**
isOddLeaf was undefined, it was isOdd

### CODE REVIEW

**Review by SiddheshKukade — APPROVED** [review]
Great !

**Comment by SiddheshKukade** [comment]
@KedarKK1 Thanks man for fixing the bug.

**Comment by KedarKK1** [comment]
@no problem, open-source os fun. BTW, you're solutions are big time-savers for us web3 enthusiasts to in a hectic schedule. A big thanks to you too.

**Comment by SiddheshKukade** [comment]
@KedarKK1 Thanks, It's not only me but love and efforts from the overall community of AU BootCamp. 😄

**Pull request merged**
