### PR TITLE
complete week 1 project

### PR DESCRIPTION
**Pull request by pokhrelanmol**
Complete week 1 ecdsa-node project is here. please review and let me know. Also i have attached the live url for the site in the readme of ecdsa-node directory

### CODE REVIEW

**Comment by SiddheshKukade** [comment]
Thanks @pokhrelanmol  I will review it in a few minutes

**Comment by pokhrelanmol** [comment]
Hey, waiting for the merger.

**Comment by SiddheshKukade** [comment]
> Hey, waiting for the merger.
> 

Hey man just checked running versions completely awesome 💥

**Comment by SiddheshKukade** [comment]
Great work @pokhrelanmol  ethereum community is proud of you 👏👏👏

**Comment by SiddheshKukade** [comment]
@pokhrelanmol did you check the message from dan from discord he really liked your project and wanted you to present that on the show yesterday . What do you think ?

**Comment by pokhrelanmol** [comment]
We can do it on another town hall.

**Pull request merged**
