### PR TITLE
added proof-of-work solutions

### PR DESCRIPTION
**Pull request by pokhrelanmol**

### CODE REVIEW

**Comment by SiddheshKukade** [comment]
@pokhrelanmol  Thanks for Helping the Ethrerum Community

**Review by SiddheshKukade — COMMENTED** [review]
The code is well-formatted and looks perfect.

**Comment by SiddheshKukade** [comment]
@pokhrelanmol  I will shift your code to the `BlockChain Cryptography` folder because it is the folder for the 1st week's content. Okay ?

**Comment by pokhrelanmol** [comment]
Okay, no problem

**Pull request merged**
